### ISSUE TITLE
Build fails on node v0.11.14

### ISSUE THREAD

**Issue by mehcode** [andrewrk/node-groove#11]
```
> groove@2.2.6 install /home/rleckey/node_modules/groove
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/rleckey/node_modules/groove/build'
  CXX(target) Release/obj.target/groove/src/groove.o
In file included from ../src/groove.cc:3:0:
../src/gn_file.h:8:40: error: expected class-name before ‘{’ token
 class GNFile : public node::ObjectWrap {
                                        ^
../src/gn_file.h:13:53: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Open(const v8::Arguments& args);
                                                     ^
../src/gn_file.h:21:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                    ^
../src/gn_file.h:24:27: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
                 const v8::AccessorInfo &info);
                           ^
../src/gn_file.h:26:27: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
                 const v8::AccessorInfo &info);
                           ^
../src/gn_file.h:28:27: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
                 const v8::AccessorInfo &info);
                           ^
../src/gn_file.h:30:54: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Close(const v8::Arguments& args);
                                                      ^
../src/gn_file.h:31:57: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Duration(const v8::Arguments& args);
                                                         ^
../src/gn_file.h:32:60: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> GetMetadata(const v8::Arguments& args);
                                                            ^
../src/gn_file.h:33:60: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> SetMetadata(const v8::Arguments& args);
                                                            ^
../src/gn_file.h:34:57: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Metadata(const v8::Arguments& args);
                                                         ^
../src/gn_file.h:35:59: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> ShortNames(const v8::Arguments& args);
                                                           ^
../src/gn_file.h:36:53: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Save(const v8::Arguments& args);
                                                     ^
In file included from ../src/groove.cc:4:0:
../src/gn_player.h:8:42: error: expected class-name before ‘{’ token
 class GNPlayer : public node::ObjectWrap {
                                          ^
../src/gn_player.h:13:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Create(const v8::Arguments& args);
                                                       ^
../src/gn_player.h:16:13: error: ‘uv_thread_t’ does not name a type
             uv_thread_t event_thread;
             ^
../src/gn_player.h:17:13: error: ‘uv_async_t’ does not name a type
             uv_async_t event_async;
             ^
../src/gn_player.h:18:13: error: ‘uv_cond_t’ does not name a type
             uv_cond_t cond;
             ^
../src/gn_player.h:19:13: error: ‘uv_mutex_t’ does not name a type
             uv_mutex_t mutex;
             ^
../src/gn_player.h:33:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                    ^
../src/gn_player.h:36:27: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
                 const v8::AccessorInfo &info);
                           ^
../src/gn_player.h:39:59: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
                 v8::Local<v8::String> property, const v8::AccessorInfo &info);
                                                           ^
../src/gn_player.h:41:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Attach(const v8::Arguments& args);
                                                       ^
../src/gn_player.h:42:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Detach(const v8::Arguments& args);
                                                       ^
../src/gn_player.h:43:57: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Position(const v8::Arguments& args);
                                                         ^
In file included from ../src/groove.cc:5:0:
../src/gn_playlist.h:8:44: error: expected class-name before ‘{’ token
 class GNPlaylist : public node::ObjectWrap {
                                            ^
../src/gn_playlist.h:13:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Create(const v8::Arguments& args);
                                                       ^
../src/gn_playlist.h:23:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                    ^
../src/gn_playlist.h:26:27: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
                 const v8::AccessorInfo &info);
                           ^
../src/gn_playlist.h:28:27: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
                 const v8::AccessorInfo &info);
                           ^
../src/gn_playlist.h:30:57: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Playlist(const v8::Arguments& args);
                                                         ^
../src/gn_playlist.h:31:53: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Play(const v8::Arguments& args);
                                                     ^
../src/gn_playlist.h:32:54: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Pause(const v8::Arguments& args);
                                                      ^
../src/gn_playlist.h:33:53: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Seek(const v8::Arguments& args);
                                                     ^
../src/gn_playlist.h:34:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Insert(const v8::Arguments& args);
                                                       ^
../src/gn_playlist.h:35:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Remove(const v8::Arguments& args);
                                                       ^
../src/gn_playlist.h:36:57: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Position(const v8::Arguments& args);
                                                         ^
../src/gn_playlist.h:37:63: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> DecodePosition(const v8::Arguments& args);
                                                               ^
../src/gn_playlist.h:38:56: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Playing(const v8::Arguments& args);
                                                        ^
../src/gn_playlist.h:39:54: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Clear(const v8::Arguments& args);
                                                      ^
../src/gn_playlist.h:40:54: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Count(const v8::Arguments& args);
                                                      ^
../src/gn_playlist.h:41:60: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> SetItemGain(const v8::Arguments& args);
                                                            ^
../src/gn_playlist.h:42:60: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> SetItemPeak(const v8::Arguments& args);
                                                            ^
../src/gn_playlist.h:43:56: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> SetGain(const v8::Arguments& args);
                                                        ^
../src/gn_playlist.h:44:60: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> SetFillMode(const v8::Arguments& args);
                                                            ^
In file included from ../src/groove.cc:6:0:
../src/gn_playlist_item.h:8:48: error: expected class-name before ‘{’ token
 class GNPlaylistItem : public node::ObjectWrap {
                                                ^
../src/gn_playlist_item.h:19:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                    ^
../src/gn_playlist_item.h:22:27: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
                 const v8::AccessorInfo &info);
                           ^
../src/gn_playlist_item.h:24:27: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
                 const v8::AccessorInfo &info);
                           ^
../src/gn_playlist_item.h:26:27: error: ‘AccessorInfo’ in namespace ‘v8’ does not name a type
                 const v8::AccessorInfo &info);
                           ^
In file included from ../src/groove.cc:7:0:
../src/gn_loudness_detector.h:8:52: error: expected class-name before ‘{’ token
 class GNLoudnessDetector : public node::ObjectWrap {
                                                    ^
../src/gn_loudness_detector.h:13:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Create(const v8::Arguments& args);
                                                       ^
../src/gn_loudness_detector.h:17:13: error: ‘uv_thread_t’ does not name a type
             uv_thread_t event_thread;
             ^
../src/gn_loudness_detector.h:18:13: error: ‘uv_async_t’ does not name a type
             uv_async_t event_async;
             ^
../src/gn_loudness_detector.h:19:13: error: ‘uv_cond_t’ does not name a type
             uv_cond_t cond;
             ^
../src/gn_loudness_detector.h:20:13: error: ‘uv_mutex_t’ does not name a type
             uv_mutex_t mutex;
             ^
../src/gn_loudness_detector.h:33:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                    ^
../src/gn_loudness_detector.h:35:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Attach(const v8::Arguments& args);
                                                       ^
../src/gn_loudness_detector.h:36:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Detach(const v8::Arguments& args);
                                                       ^
../src/gn_loudness_detector.h:37:56: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> GetInfo(const v8::Arguments& args);
                                                        ^
../src/gn_loudness_detector.h:38:57: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Position(const v8::Arguments& args);
                                                         ^
In file included from ../src/groove.cc:8:0:
../src/gn_fingerprinter.h:8:49: error: expected class-name before ‘{’ token
 class GNFingerprinter : public node::ObjectWrap {
                                                 ^
../src/gn_fingerprinter.h:13:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Create(const v8::Arguments& args);
                                                       ^
../src/gn_fingerprinter.h:15:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Encode(const v8::Arguments& args);
                                                       ^
../src/gn_fingerprinter.h:16:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Decode(const v8::Arguments& args);
                                                       ^
../src/gn_fingerprinter.h:19:13: error: ‘uv_thread_t’ does not name a type
             uv_thread_t event_thread;
             ^
../src/gn_fingerprinter.h:20:13: error: ‘uv_async_t’ does not name a type
             uv_async_t event_async;
             ^
../src/gn_fingerprinter.h:21:13: error: ‘uv_cond_t’ does not name a type
             uv_cond_t cond;
             ^
../src/gn_fingerprinter.h:22:13: error: ‘uv_mutex_t’ does not name a type
             uv_mutex_t mutex;
             ^
../src/gn_fingerprinter.h:35:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                    ^
../src/gn_fingerprinter.h:37:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Attach(const v8::Arguments& args);
                                                       ^
../src/gn_fingerprinter.h:38:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Detach(const v8::Arguments& args);
                                                       ^
../src/gn_fingerprinter.h:39:56: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> GetInfo(const v8::Arguments& args);
                                                        ^
../src/gn_fingerprinter.h:40:57: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Position(const v8::Arguments& args);
                                                         ^
In file included from ../src/groove.cc:9:0:
../src/gn_encoder.h:8:43: error: expected class-name before ‘{’ token
 class GNEncoder : public node::ObjectWrap {
                                           ^
../src/gn_encoder.h:13:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Create(const v8::Arguments& args);
                                                       ^
../src/gn_encoder.h:16:13: error: ‘uv_thread_t’ does not name a type
             uv_thread_t event_thread;
             ^
../src/gn_encoder.h:17:13: error: ‘uv_async_t’ does not name a type
             uv_async_t event_async;
             ^
../src/gn_encoder.h:18:13: error: ‘uv_cond_t’ does not name a type
             uv_cond_t cond;
             ^
../src/gn_encoder.h:19:13: error: ‘uv_mutex_t’ does not name a type
             uv_mutex_t mutex;
             ^
../src/gn_encoder.h:31:52: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> New(const v8::Arguments& args);
                                                    ^
../src/gn_encoder.h:33:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Attach(const v8::Arguments& args);
                                                       ^
../src/gn_encoder.h:34:55: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Detach(const v8::Arguments& args);
                                                       ^
../src/gn_encoder.h:35:58: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> GetBuffer(const v8::Arguments& args);
                                                          ^
../src/gn_encoder.h:36:57: error: ‘Arguments’ in namespace ‘v8’ does not name a type
         static v8::Handle<v8::Value> Position(const v8::Arguments& args);
                                                         ^
../src/groove.cc:14:32: error: ‘Arguments’ does not name a type
 Handle<Value> SetLogging(const Arguments& args) {
                                ^
In file included from /home/rleckey/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/groove.cc:1:
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> SetLogging(const int&)’:
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/groove.cc:15:17: error: within this context
     HandleScope scope;
                 ^
../src/groove.cc:17:14: error: request for member ‘Length’ in ‘args’, which is of non-class type ‘const int’
     if (args.Length() < 1 || !args[0]->IsNumber()) {
              ^
../src/groove.cc:17:37: error: invalid types ‘const int[int]’ for array subscript
     if (args.Length() < 1 || !args[0]->IsNumber()) {
                                     ^
../src/groove.cc:18:45: error: ‘New’ is not a member of ‘v8::String’
         ThrowException(Exception::TypeError(String::New("Expected 1 number argument")));
                                             ^
../src/groove.cc:18:87: error: ‘ThrowException’ was not declared in this scope
         ThrowException(Exception::TypeError(String::New("Expected 1 number argument")));
                                                                                       ^
../src/groove.cc:19:22: error: ‘class v8::HandleScope’ has no member named ‘Close’
         return scope.Close(Undefined());
                      ^
../src/groove.cc:19:38: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
         return scope.Close(Undefined());
                                      ^
In file included from /home/rleckey/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/groove.cc:1:
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:305:28: note: declared here
   friend Handle<Primitive> Undefined(Isolate* isolate);
                            ^
../src/groove.cc:21:30: error: invalid types ‘const int[int]’ for array subscript
     groove_set_logging(args[0]->NumberValue());
                              ^
../src/groove.cc:22:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(Undefined());
                  ^
../src/groove.cc:22:34: error: too few arguments to function ‘v8::Handle<v8::Primitive> v8::Undefined(v8::Isolate*)’
     return scope.Close(Undefined());
                                  ^
In file included from /home/rleckey/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/groove.cc:1:
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:305:28: note: declared here
   friend Handle<Primitive> Undefined(Isolate* isolate);
                            ^
../src/groove.cc: At global scope:
../src/groove.cc:25:32: error: ‘Arguments’ does not name a type
 Handle<Value> GetDevices(const Arguments& args) {
                                ^
In file included from /home/rleckey/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/groove.cc:1:
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> GetDevices(const int&)’:
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/groove.cc:26:17: error: within this context
     HandleScope scope;
                 ^
../src/groove.cc:28:42: error: no matching function for call to ‘v8::Array::New()’
     Local<Array> deviceList = Array::New();
                                          ^
../src/groove.cc:28:42: note: candidate is:
In file included from /home/rleckey/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/groove.cc:1:
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:2401:23: note: static v8::Local<v8::Array> v8::Array::New(v8::Isolate*, int)
   static Local<Array> New(Isolate* isolate, int length = 0);
                       ^
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:2401:23: note:   candidate expects 2 arguments, 0 provided
../src/groove.cc:32:38: error: no matching function for call to ‘v8::Number::New(int&)’
         deviceList->Set(Number::New(i), String::New(name));
                                      ^
../src/groove.cc:32:38: note: candidate is:
In file included from /home/rleckey/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/groove.cc:1:
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:1976:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:1976:24: note:   candidate expects 2 arguments, 1 provided
../src/groove.cc:32:41: error: ‘New’ is not a member of ‘v8::String’
         deviceList->Set(Number::New(i), String::New(name));
                                         ^
../src/groove.cc:34:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(deviceList);
                  ^
../src/groove.cc: At global scope:
../src/groove.cc:37:32: error: ‘Arguments’ does not name a type
 Handle<Value> GetVersion(const Arguments& args) {
                                ^
In file included from /home/rleckey/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/groove.cc:1:
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h: In function ‘v8::Handle<v8::Value> GetVersion(const int&)’:
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:816:13: error: ‘v8::HandleScope::HandleScope()’ is protected
   V8_INLINE HandleScope() {}
             ^
../src/groove.cc:38:17: error: within this context
     HandleScope scope;
                 ^
../src/groove.cc:40:41: error: no matching function for call to ‘v8::Object::New()’
     Local<Object> version = Object::New();
                                         ^
../src/groove.cc:40:41: note: candidate is:
In file included from /home/rleckey/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/groove.cc:1:
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:2372:24: note: static v8::Local<v8::Object> v8::Object::New(v8::Isolate*)
   static Local<Object> New(Isolate* isolate);
                        ^
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:2372:24: note:   candidate expects 1 argument, 0 provided
../src/groove.cc:41:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     version->Set(String::NewSymbol("major"), Number::New(groove_version_major()));
                  ^
../src/groove.cc:41:80: error: no matching function for call to ‘v8::Number::New(int)’
     version->Set(String::NewSymbol("major"), Number::New(groove_version_major()));
                                                                                ^
../src/groove.cc:41:80: note: candidate is:
In file included from /home/rleckey/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/groove.cc:1:
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:1976:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:1976:24: note:   candidate expects 2 arguments, 1 provided
../src/groove.cc:42:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     version->Set(String::NewSymbol("minor"), Number::New(groove_version_minor()));
                  ^
../src/groove.cc:42:80: error: no matching function for call to ‘v8::Number::New(int)’
     version->Set(String::NewSymbol("minor"), Number::New(groove_version_minor()));
                                                                                ^
../src/groove.cc:42:80: note: candidate is:
In file included from /home/rleckey/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/groove.cc:1:
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:1976:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:1976:24: note:   candidate expects 2 arguments, 1 provided
../src/groove.cc:43:18: error: ‘NewSymbol’ is not a member of ‘v8::String’
     version->Set(String::NewSymbol("patch"), Number::New(groove_version_patch()));
                  ^
../src/groove.cc:43:80: error: no matching function for call to ‘v8::Number::New(int)’
     version->Set(String::NewSymbol("patch"), Number::New(groove_version_patch()));
                                                                                ^
../src/groove.cc:43:80: note: candidate is:
In file included from /home/rleckey/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/groove.cc:1:
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:1976:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:1976:24: note:   candidate expects 2 arguments, 1 provided
../src/groove.cc:44:18: error: ‘class v8::HandleScope’ has no member named ‘Close’
     return scope.Close(version);
                  ^
../src/groove.cc: In function ‘void SetProperty(target_t, const char*, double)’:
../src/groove.cc:49:14: error: ‘NewSymbol’ is not a member of ‘v8::String’
     obj->Set(String::NewSymbol(name), Number::New(n));
              ^
../src/groove.cc:49:52: error: no matching function for call to ‘v8::Number::New(double&)’
     obj->Set(String::NewSymbol(name), Number::New(n));
                                                    ^
../src/groove.cc:49:52: note: candidate is:
In file included from /home/rleckey/.node-gyp/0.11.14/src/node.h:61:0,
                 from ../src/groove.cc:1:
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:1976:24: note: static v8::Local<v8::Number> v8::Number::New(v8::Isolate*, double)
   static Local<Number> New(Isolate* isolate, double value);
                        ^
/home/rleckey/.node-gyp/0.11.14/deps/v8/include/v8.h:1976:24: note:   candidate expects 2 arguments, 1 provided
../src/groove.cc: In function ‘void Initialize(v8::Handle<v8::Object>)’:
../src/groove.cc:79:48: error: ‘SetMethod’ was not declared in this scope
     SetMethod(exports, "setLogging", SetLogging);
                                                ^
../src/groove.cc: In function ‘v8::Handle<v8::Value> SetLogging(const int&)’:
../src/groove.cc:23:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/groove.cc: In function ‘v8::Handle<v8::Value> GetDevices(const int&)’:
../src/groove.cc:35:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/groove.cc: In function ‘v8::Handle<v8::Value> GetVersion(const int&)’:
../src/groove.cc:45:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
groove.target.mk:91: recipe for target 'Release/obj.target/groove/src/groove.o' failed
make: *** [Release/obj.target/groove/src/groove.o] Error 1
make: Leaving directory '/home/rleckey/node_modules/groove/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/rleckey/.nvm/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1059:12)
gyp ERR! System Linux 3.17.2-1-ARCH
gyp ERR! command "node" "/home/rleckey/.nvm/v0.11.14/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/rleckey/node_modules/groove
gyp ERR! node -v v0.11.14
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 

npm ERR! Linux 3.17.2-1-ARCH
npm ERR! argv "/home/rleckey/.nvm/v0.11.14/bin/node" "/home/rleckey/.nvm/v0.11.14/bin/npm" "i" "groove"
npm ERR! node v0.11.14
npm ERR! npm  v2.0.0
npm ERR! code ELIFECYCLE
npm ERR! groove@2.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the groove@2.2.6 install script.
npm ERR! This is most likely a problem with the groove package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls groove
npm ERR! There is likely additional logging output above.
```

**Comment by christophgysin** [comment]
nodejs 0.12 has been released, and archlinux ships with it. Any chance to get node-groove to compile against nodejs 0.12?

**Comment by andrewrk** [comment]
Alright. I'll get started on this. I'm going to use node-nan which will provide compatibility with 0.12 as well as io.js

**Comment by andrewrk** [comment]
@christophgysin published with this change, also updated groovebasin master branch to work with node v0.12.

**Comment by christophgysin** [comment]
Excellent, thanks!
