### ISSUE TITLE
cannot install node-groove

### ISSUE THREAD

**Issue by miketamis** [andrewrk/node-groove#28]
I cannot install node-groove I get this error:

```
Mikes-MacBook-2:RelayPlayer miketamis$ npm i groove --save

> groove@2.5.0 install /Users/miketamis/Development/MusicPlayer/RelayPlayer/node_modules/groove
> node-gyp rebuild

  CXX(target) Release/obj.target/groove/src/groove.o
In file included from ../src/groove.cc:2:
../node_modules/nan/nan.h:602:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:608:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:613:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:619:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
../src/groove.cc:60:5: error: use of undeclared identifier 'groove_init'
    groove_init();
    ^
../src/groove.cc:61:12: error: use of undeclared identifier 'groove_finish'
    atexit(groove_finish);
           ^
../src/groove.cc:80:44: error: use of undeclared identifier 'GROOVE_EVERY_SINK_FULL'
    SetProperty(target, "EVERY_SINK_FULL", GROOVE_EVERY_SINK_FULL);
                                           ^
../src/groove.cc:81:42: error: use of undeclared identifier 'GROOVE_ANY_SINK_FULL'
    SetProperty(target, "ANY_SINK_FULL", GROOVE_ANY_SINK_FULL);
                                         ^
8 errors generated.
make: *** [Release/obj.target/groove/src/groove.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/usr/local/Cellar/node/6.2.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/miketamis/Development/MusicPlayer/RelayPlayer/node_modules/groove
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
relay-player@1.0.0 /Users/miketamis/Development/MusicPlayer/RelayPlayer
├── babel@6.5.2  extraneous
├── babel-cli@6.9.0  extraneous
├── babel-preset-es2015@6.9.0  extraneous
├── systemjs@0.19.29  extraneous
├── traceur@0.0.110  extraneous
└── typescript@1.8.10  extraneous
```

**Comment by miketamis** [comment]
Fixed it by install from github  npm i https://github.com/andrewrk/node-groove/tarball/master

https://github.com/andrewrk/node-groove/commit/85b902b53fef3358cf61b318f86247337794e720 
fixes my problem

**Comment by Beatusvir** [comment]
Nice, thanks @miketamis I was also stuck trying to install this. I had no idea I could install from github repo.

**Comment by txchen** [comment]
I have the same issue, on OSX. 

Install from github tarball does not work for me, it is complaining .h file not found.

**Comment by txchen** [comment]
My error:
```
> npm install groove

> groove@2.5.0 install /Users/txchen/localcode/groovetest/node_modules/groove
> node-gyp rebuild

  CXX(target) Release/obj.target/groove/src/groove.o
In file included from ../src/groove.cc:2:
../../nan/nan.h:602:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:608:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:613:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:619:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/groove/src/groove.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/txchen/localcode/groovetest/node_modules/groove
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/Users/txchen/localcode/groovetest/package.json'
npm WARN groovetest No description
npm WARN groovetest No repository field.
npm WARN groovetest No README data
npm WARN groovetest No license field.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "install" "groove"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! groove@2.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the groove@2.5.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the groove package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs groove
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls groove
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/txchen/localcode/groovetest/npm-debug.log
```

**Comment by andrewrk** [comment]
This is all because I haven't released the new version yet. Still pending some libgroove changes.

**Comment by thejoshwolfe** [comment]
the nan error can be fixed by updating node-groove's dependency on nan. i did this locally to work around the issue.

**Comment by andrewrk** [comment]
Try 2.5.1

**Comment by txchen** [comment]
@andrewrk Now I can npm install 2.5.1
However when I run the example/playlist.js, I got this error (on OSX)

```
groove.connectSoundBackend();
       ^

TypeError: groove.connectSoundBackend is not a function
    at Object.<anonymous> (/Users/txchen/localcode/groovetest/index.js:11:8)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
```

**Comment by andrewrk** [comment]
Master branch depends on libgroove 5.0.0 which is not released yet. Branch 2.x is what you probably want to play with right now.
