### ISSUE TITLE
libgroove is installed but saying that cant open shared...

### ISSUE THREAD

**Issue by gartz** [andrewrk/node-groove#5]
I'm using Fedora 20, have installed libgroove:

```
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/libgroove.a
-- Installing: /usr/local/include/groove/groove.h
-- Installing: /usr/local/include/groove/queue.h
-- Installing: /usr/local/include/groove/encoder.h
-- Installing: /usr/local/lib/libgroove.so.3.1.1
-- Installing: /usr/local/lib/libgroove.so.3
-- Installing: /usr/local/lib/libgroove.so
-- Removed runtime path from "/usr/local/lib/libgroove.so.3.1.1"
-- Installing: /usr/local/include/grooveplayer/player.h
-- Installing: /usr/local/lib/libgrooveplayer.so.3.1.1
-- Installing: /usr/local/lib/libgrooveplayer.so.3
-- Installing: /usr/local/lib/libgrooveplayer.so
-- Removed runtime path from "/usr/local/lib/libgrooveplayer.so.3.1.1"
-- Installing: /usr/local/lib/libgrooveplayer.a
-- Installing: /usr/local/include/grooveloudness/loudness.h
-- Installing: /usr/local/lib/libgrooveloudness.so.3.1.1
-- Installing: /usr/local/lib/libgrooveloudness.so.3
-- Installing: /usr/local/lib/libgrooveloudness.so
-- Removed runtime path from "/usr/local/lib/libgrooveloudness.so.3.1.1"
-- Installing: /usr/local/lib/libgrooveloudness.a
-- Installing: /usr/local/include/groovefingerprinter/fingerprinter.h
-- Installing: /usr/local/lib/libgroovefingerprinter.so.3.1.1
-- Installing: /usr/local/lib/libgroovefingerprinter.so.3
-- Installing: /usr/local/lib/libgroovefingerprinter.so
-- Removed runtime path from "/usr/local/lib/libgroovefingerprinter.so.3.1.1"
-- Installing: /usr/local/lib/libgroovefingerprinter.a
```

But when I try to run the project it is showing this error:

```
/home/gartz/Projects/groovebasin/node_modules/groove/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: libgroove.so.3: cannot open shared object file: No such file or directory
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at bindings (/home/gartz/Projects/groovebasin/node_modules/groove/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/gartz/Projects/groovebasin/node_modules/groove/lib/index.js:1:97)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
npm ERR! weird error 8
npm ERR! not ok code 0
npm ERR! weird error 1
npm ERR! not ok code 0
```

I don't know what to do, because the lib is already installed.

**Comment by gartz** [comment]
Você foi convidado!

Seu amigo Gabriel te fez ganhar $50 na sua primeira viagem no Airbnb, a melhor maneira de viajar. Seja legal e lembre-se de agradecer!

Valor mínimo de reserva $200.

Resgate o seu crédito de $50
http://www.airbnb.com.br/c/ggartz?euid=9a2163ae-4756-a7c9-632d-760f24002b18&ri=11840580&s=1

Obrigado,
A Equipe do Airbnb

P.O. Box 410807, San Francisco, CA 94121

Cancelar
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkraS0zMjE4MjAxMC0yOTY3NDE4ZjZjMGI5YTU3MjA0YmU3ZTY1MzkxNDQwOTIxOTFkM2RiLTk5NjA4QHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbiIsInV1aWQiOiI5YTIxNjNhZS00NzU2LWE3YzktNjMyZC03NjBmMjQwMDJiMTgifQ==&mac=Y52l4XKrDdYskiW9F0MgTHJxlGg=

### Airbnb ###
